#!/usr/bin/tclsh
package require Expect
#!//usr/bin/expect -f
#set cmd [lrange $argv 0 end]
#set dest [lindex $argv 0]
#set port_d [lindex $argv 1]
#set source [lindex $argv 2]
#set port_s [lindex $argv 3]
#set bw [lindex $argv 4]
#set duration [lindex $argv 5]
set timeout 3
set f [open "~/Traffic_Generation/tra.conf"]
set tra_flow [split [read  $f] "\n\r"]
close $f
puts "num of line:[llength $tra_flow]"
foreach flow $tra_flow {
    if {$flow == ""} {
        break;
    }
    puts  "???????????[string index $flow 0]"
    if { [string index $flow 0] == "#"} {
        
        continue;
    }
	set arg [split $flow " "]

	set dest [lindex $arg 0]
	set port_d [lindex $arg 1]
	set sourc [lindex $arg 2]
	set port_s [lindex $arg 3]
	set bw [lindex $arg 4]
	set duration [lindex $arg 5]
	set dest_ip [string range $dest [string first "@" $dest]+1 end]
	puts "&&&&&&&&&&&&&&&$dest  $dest_ip"
	#spawn ssh -p 3022 junlab@140.113.13.136
	eval spawn ssh -p $port_d $dest 
	expect "assword"
	send "6\n"
	expect "@"
	send "iperf -s -u -i 1 & disown\n"
	expect "listening"
	send "logout\n"
	#interact timeout 1 return
    interact


	#eval spawn ssh -p 3033 jun@140.113.13.138
	eval spawn ssh -p $port_s $sourc 
	expect "assword"
	send "6\n"
	expect "@"
	send "iperf -c $dest_ip -p $port_d -t $duration -i 1 -b $bw & disown\n"
	expect "connecting"

	send "logout\n"
	interact 
    

	#break;
	#interact timeout 1 return
}


##spawn ssh -p 3022 junlab@140.113.13.136
#eval spawn ssh -p $port_d $dest
#expect " "
#send "6\n"
#expect "@"
#send "echo hello\n"
#expect "@"
##interact timeout 1 return
#send "iperf -s -u -i 1 & disown\n"
##interact  timeout 1 return
#interact
#
##spawn ssh -p 3033 jun@140.113.13.138
##expect " "
##send "6\n"
##expect "jun"
##send "echo hello\n"
##expect "jun"
##send "iperf -c 140.113.13.136 -p 8000 -t 5 -i 1 -b 100K & disown\n"
##interact timeout 1 return
